name: food_app
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.50.1
  animations: ^2.0.0
  syncfusion_flutter_gauges: ^20.1.61
  contained_tab_bar_view: ^0.8.0
  flutter_speed_dial: ^5.1.0
  font_awesome_flutter: ^10.1.0
  flutter_screenutil: ^5.4.0
  firebase_core: ^1.14.1
  cloud_firestore: ^3.1.12
  firebase_auth: ^3.3.17
  flutter_riverpod: ^1.0.3

  
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - images/


